# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-01 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PCR_Polymerase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_seq', models.CharField(max_length=200)),
                ('product_name', models.CharField(max_length=200)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('product_factory', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date produced')),
            ],
        ),
    ]
