# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pcr_polymerase',
            old_name='product_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='pcr_polymerase',
            old_name='pub_date',
            new_name='pro_date',
        ),
        migrations.RemoveField(
            model_name='pcr_polymerase',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pcr_polymerase',
            name='product_factory',
        ),
        migrations.RemoveField(
            model_name='pcr_polymerase',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='pcr_polymerase',
            name='product_seq',
        ),
        migrations.AddField(
            model_name='pcr_polymerase',
            name='category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pcr_polymerase',
            name='factory',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pcr_polymerase',
            name='lifetime',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pcr_polymerase',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pcr_polymerase',
            name='seqNo',
            field=models.CharField(blank=True, max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='pcr_polymerase',
            name='unit',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
