# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20160108_0201'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenchTop',
            fields=[
                ('seqNo', models.CharField(blank=True, max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('factory', models.CharField(blank=True, max_length=200, null=True)),
                ('pro_date', models.DateTimeField(verbose_name='date produced')),
                ('unit', models.CharField(blank=True, max_length=200, null=True)),
                ('category', models.CharField(blank=True, max_length=200, null=True)),
                ('lifetime', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
