# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_benchtop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benchtop',
            name='lifetime',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
